name = "ThermovisorData"
uuid = "54d963ed-1681-434b-92d2-200df9375a55"
authors = ["Roman Mironov"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
